# Name of the microservice.
#microservice_name: kypo-sandbox-service

# A boolean that turns on/off debug mode.
# SECURITY WARNING: don't run with debug turned on in production!
debug: True

# A list of strings representing the host/domain names that this Django site can serve.
#allowed_hosts: []

# If True, the whitelist will not be used and all origins will be accepted.
#cors_origin_allow_all: True

# A list of origins that are authorized to make cross-site HTTP requests.
#cors_origin_whitelist: []

application_configuration:
    # A path to directory of CA certificates or file of CA certificates, i.e. CA bundle.
    # Use in case of self-signed certificates in related services.
    ssl_ca_certificate_verify: ""
