[tox]
envlist = pre-commit, pylint, bandit, audit, pytest

[testenv]
ignore_outcome = True
deps =
    pytest
    pytest-mock
    pytest-structlog
setenv = DJANGO_SETTINGS_MODULE=crczp.mitre_technique_project.tests.settings
passenv = PYPI_DOWNLOAD_URL

[testenv:pylint]
deps =
    {[testenv]deps}
    pylint
commands = pylint crczp tests --output-format=colorized --fail-under=9.5

[testenv:bandit]
deps = bandit
commands = bandit -r crczp -c pyproject.toml

[testenv:audit]
deps = pip-audit
commands = pip-audit --progress-spinner=off .

[testenv:pytest]
commands = pytest -m "not integration" --basetemp={envtmpdir} {posargs} -s
           python manage.py check

# pre-commit covers ruff lint, ruff format, mypy
[testenv:pre-commit]
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure
